[logging]
file_log = true
console_log = true

[logging.file]
dir = "./logs"
name = "test.log"
rolling = "daily"
level = "DEBUG"
json = false

[logging.console]
level = "DEBUG"
pretty = true

[account]
name = "test"
csv_path = "./config/test_account_info.csv"
