[package]
name = "trading-core"
version = "0.1.0"
edition = "2024"

[features]
testnet = ["data/testnet"]

[dependencies]
data = { path = "../data" }
rust_decimal = { workspace = true, features = ["macros", "serde"] }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
futures-util = { workspace = true }

derive_more = { workspace = true }

enum-map = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
chrono = { workspace = true }

url = { workspace = true }
hmac = "0.13"
sha2 = "0.11"
hex = "0.4"
serde_urlencoded = "0.7"

openssl = { workspace = true }
